name: Multi-Environment Deployment to Azure Static Web Apps

on:
  push:
    branches:
      - master
      - develop

env:
  NODE_VERSION: '18'

jobs:
  # Build job - chạy cho tất cả các trường hợp
  build_job:
    runs-on: ubuntu-latest
    name: Build Next.js App
    outputs:
      build_output: ${{ steps.build.outputs.build_output }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        id: build
        run: |
          npm run build
          echo "build_output=out" >> $GITHUB_OUTPUT
        env:
          CI: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: out/
          retention-days: 1

  # Deploy to Development Environment (tự động)
  deploy_dev_job:
    needs: build_job
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Development
    environment: development
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: out/

      - name: Deploy to Azure Static Web Apps - Development
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_DEV_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out"
          output_location: ""
          skip_app_build: true
          deployment_environment: development
          api_location: ""
          api_build_command: ""

  # Deploy to Production Environment (cần approval)
  deploy_prod_job:
    needs: build_job
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Deploy to Production
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: out/

      - name: Deploy to Azure Static Web Apps - Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_PROD_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "out"
          output_location: ""
          skip_app_build: true
          api_location: ""
          api_build_command: ""

